
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/luigidomenicocastano/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 23.0.0 - arm64
